(define (problem all-out-p)
    (:domain all-out-d)
    (:objects 
        coin11 coin12 coin13 coin14 coin15
        coin21 coin22 coin23 coin24 coin25
        coin31 coin32 coin33 coin34 coin35
        coin41 coin42 coin43 coin44 coin45
        coin51 coin52 coin53 coin54 coin55
    )
    (:init
        ; init adjacency
        ; row 1
        ; column 1
        (not (is-adjacent coin11 coin11))
        (is-adjacent coin11 coin12)
        (is-adjacent coin11 coin21)
        (has-two-neighbours coin11)
        (not (has-three-neighbours coin11))
        (not (has-four-neighbours coin11))
        ; column 2
        (not (is-adjacent coin12 coin12))
        (is-adjacent coin12 coin11)
        (is-adjacent coin12 coin22)
        (is-adjacent coin12 coin13)
        (not (has-two-neighbours coin12))
        (has-three-neighbours coin12)
        (not (has-four-neighbours coin12))
        ; column 3
        (not (is-adjacent coin13 coin13))
        (is-adjacent coin13 coin12)
        (is-adjacent coin13 coin23)
        (is-adjacent coin13 coin14)
        (not (has-two-neighbours coin13))
        (has-three-neighbours coin13)
        (not (has-four-neighbours coin13))
        ; column 4
        (not (is-adjacent coin14 coin14))
        (is-adjacent coin14 coin13)
        (is-adjacent coin14 coin24)
        (is-adjacent coin14 coin15)
        (not (has-two-neighbours coin14))
        (has-three-neighbours coin14)
        (not (has-four-neighbours coin14))
        ; column 5
        (not (is-adjacent coin15 coin15))
        (is-adjacent coin15 coin14)
        (is-adjacent coin15 coin25)
        (has-two-neighbours coin15)
        (not (has-three-neighbours coin15))
        (not (has-four-neighbours coin15))

        ; row 2
        ; column 1
        (not (is-adjacent coin21 coin21))
        (is-adjacent coin21 coin11)
        (is-adjacent coin21 coin22)
        (is-adjacent coin21 coin31)
        (not (has-two-neighbours coin21))
        (has-three-neighbours coin21)
        (not (has-four-neighbours coin21))
        ; column 2
        (not (is-adjacent coin22 coin22))
        (is-adjacent coin22 coin21)
        (is-adjacent coin22 coin12)
        (is-adjacent coin22 coin32)
        (is-adjacent coin22 coin23)
        (not (has-two-neighbours coin22))
        (not (has-three-neighbours coin22))
        (has-four-neighbours coin22)
        ; column 3
        (not (is-adjacent coin23 coin23))
        (is-adjacent coin23 coin22)
        (is-adjacent coin23 coin13)
        (is-adjacent coin23 coin33)
        (is-adjacent coin23 coin24)
        (not (has-two-neighbours coin23))
        (not (has-three-neighbours coin23))
        (has-four-neighbours coin23)
        ; column 4
        (not (is-adjacent coin24 coin24))
        (is-adjacent coin24 coin23)
        (is-adjacent coin24 coin14)
        (is-adjacent coin24 coin34)
        (is-adjacent coin24 coin25)
        (not (has-two-neighbours coin24))
        (not (has-three-neighbours coin24))
        (has-four-neighbours coin24)
        ; column 5
        (not (is-adjacent coin25 coin25))
        (is-adjacent coin25 coin15)
        (is-adjacent coin25 coin24)
        (is-adjacent coin25 coin35)
        (not (has-two-neighbours coin25))
        (has-three-neighbours coin25)
        (not (has-four-neighbours coin25))

        ; row 3
        ; column 1
        (not (is-adjacent coin31 coin31))
        (is-adjacent coin31 coin21)
        (is-adjacent coin31 coin32)
        (is-adjacent coin31 coin41)
        (not (has-two-neighbours coin31))
        (has-three-neighbours coin31)
        (not (has-four-neighbours coin31))
        ; column 2
        (not (is-adjacent coin32 coin32))
        (is-adjacent coin32 coin31)
        (is-adjacent coin32 coin22)
        (is-adjacent coin32 coin42)
        (is-adjacent coin32 coin33)
        (not (has-two-neighbours coin32))
        (not (has-three-neighbours coin32))
        (has-four-neighbours coin32)
        ; column 3
        (not (is-adjacent coin33 coin33))
        (is-adjacent coin33 coin32)
        (is-adjacent coin33 coin23)
        (is-adjacent coin33 coin43)
        (is-adjacent coin33 coin34)
        (not (has-two-neighbours coin33))
        (not (has-three-neighbours coin33))
        (has-four-neighbours coin33)
        ; column 4
        (not (is-adjacent coin34 coin34))
        (is-adjacent coin34 coin24)
        (is-adjacent coin34 coin33)
        (is-adjacent coin34 coin44)
        (is-adjacent coin34 coin35)
        (not (has-two-neighbours coin34))
        (not (has-three-neighbours coin34))
        (has-four-neighbours coin34)
        ; column 5
        (not (is-adjacent coin35 coin35))
        (is-adjacent coin35 coin25)
        (is-adjacent coin35 coin34)
        (is-adjacent coin35 coin45)
        (not (has-two-neighbours coin35))
        (has-three-neighbours coin35)
        (not (has-four-neighbours coin35))

        ; row 4
        ; column 1
        (not (is-adjacent coin41 coin41))
        (is-adjacent coin41 coin31)
        (is-adjacent coin41 coin42)
        (is-adjacent coin41 coin51)
        (not (has-two-neighbours coin41))
        (has-three-neighbours coin41)
        (not (has-four-neighbours coin41))
        ; column 2
        (not (is-adjacent coin42 coin42))
        (is-adjacent coin42 coin41)
        (is-adjacent coin42 coin32)
        (is-adjacent coin42 coin43)
        (is-adjacent coin42 coin52)
        (not (has-two-neighbours coin42))
        (not (has-three-neighbours coin42))
        (has-four-neighbours coin42)
        ; column 3
        (not (is-adjacent coin43 coin43))
        (is-adjacent coin43 coin42)
        (is-adjacent coin43 coin33)
        (is-adjacent coin43 coin44)
        (is-adjacent coin43 coin53)
        (not (has-two-neighbours coin43))
        (not (has-three-neighbours coin43))
        (has-four-neighbours coin43)
        ; column 4
        (not (is-adjacent coin44 coin44))
        (is-adjacent coin44 coin43)
        (is-adjacent coin44 coin34)
        (is-adjacent coin44 coin45)
        (is-adjacent coin44 coin54)
        (not (has-two-neighbours coin44))
        (not (has-three-neighbours coin44))
        (has-four-neighbours coin44)
        ; column 5
        (not (is-adjacent coin45 coin45))
        (is-adjacent coin45 coin35)
        (is-adjacent coin45 coin44)
        (is-adjacent coin45 coin55)
        (not (has-two-neighbours coin45))
        (has-three-neighbours coin45)
        (not (has-four-neighbours coin45))

        ; row 5
        ; column 1
        (not (is-adjacent coin51 coin51))
        (is-adjacent coin51 coin41)
        (is-adjacent coin51 coin52)
        (has-two-neighbours coin51)
        (not (has-three-neighbours coin51))
        (not (has-four-neighbours coin51))
        ; column 2
        (not (is-adjacent coin52 coin52))
        (is-adjacent coin52 coin51)
        (is-adjacent coin52 coin42)
        (is-adjacent coin52 coin53)
        (not (has-two-neighbours coin52))
        (has-three-neighbours coin52)
        (not (has-four-neighbours coin52))
        ; column 3
        (not (is-adjacent coin53 coin53))
        (is-adjacent coin53 coin52)
        (is-adjacent coin53 coin43)
        (is-adjacent coin53 coin54)
        (not (has-two-neighbours coin53))
        (has-three-neighbours coin53)
        (not (has-four-neighbours coin53))
        ; column 4
        (not (is-adjacent coin54 coin54))
        (is-adjacent coin54 coin53)
        (is-adjacent coin54 coin44)
        (is-adjacent coin54 coin55)
        (not (has-two-neighbours coin54))
        (has-three-neighbours coin54)
        (not (has-four-neighbours coin54))
        ;column 5
        (not (is-adjacent coin55 coin55))
        (is-adjacent coin55 coin54)
        (is-adjacent coin55 coin45)
        (has-two-neighbours coin55)
        (not (has-three-neighbours coin55))
        (not (has-four-neighbours coin55))

        ; init all coin faces down
        (not (is-up coin11))
        (not (is-up coin12))
        (not (is-up coin13))
        (not (is-up coin14))
        (not (is-up coin15))
        ; row 2
        (not (is-up coin21))
        (not (is-up coin22))
        (not (is-up coin23))
        (not (is-up coin24))
        (not (is-up coin25))
        ; row 3
        (not (is-up coin31))
        (not (is-up coin32))
        (not (is-up coin33))
        (not (is-up coin34))
        (not (is-up coin35))
        ; row 4
        (not (is-up coin41))
        (not (is-up coin42))
        (not (is-up coin43))
        (not (is-up coin44))
        (not (is-up coin45))
        ; row 5
        (not (is-up coin51))
        (not (is-up coin52))
        (not (is-up coin53))
        (not (is-up coin54))
        (not (is-up coin55))
    )
    (:goal
        (and
            ; all coin faces up
            ; row 1
            (is-up coin11)
            (is-up coin12)
            (is-up coin13)
            (is-up coin14)
            (is-up coin15)
            ; row 2
            (is-up coin21)
            (is-up coin22)
            (is-up coin23)
            (is-up coin24)
            (is-up coin25)
            ; row 3
            (is-up coin31)
            (is-up coin32)
            (is-up coin33)
            (is-up coin34)
            (is-up coin35)
            ; row 4
            (is-up coin41)
            (is-up coin42)
            (is-up coin43)
            (is-up coin44)
            (is-up coin45)
            ; row 5
            (is-up coin51)
            (is-up coin52)
            (is-up coin53)
            (is-up coin54)
            (is-up coin55)
        )
    )
)